# Generated by Django 5.2 on 2025-11-12 15:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('business_name', models.CharField(max_length=255, verbose_name='Razón Social / Nombre')),
                ('ruc', models.CharField(help_text='Registro Único de Contribuyentes', max_length=11, unique=True, verbose_name='RUC')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Contratista',
                'verbose_name_plural': 'Contratistas',
                'db_table': 'contractors',
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('description', models.CharField(help_text='Ejemplo: Nuevos soles, dólares', max_length=50, verbose_name='Descripción')),
                ('code', models.CharField(help_text='Ejemplo: PEN, USD', max_length=3, unique=True, verbose_name='Código')),
                ('symbol', models.CharField(help_text='Ejemplo: S/., $', max_length=5, verbose_name='Símbolo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Tipo de Moneda',
                'verbose_name_plural': 'Tipos de Moneda',
                'db_table': 'currency_types',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='FinancialEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('description', models.CharField(help_text='Ejemplo: SCOTIABANK PERU, NACION', max_length=50, verbose_name='Descripción')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Entidad Financiera',
                'verbose_name_plural': 'Entidades Financieras',
                'db_table': 'financial_entities',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='LetterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('description', models.CharField(help_text='Ejemplo: Adelanto de materiales, adelanto directo', max_length=50, verbose_name='Descripción')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Tipo de Carta',
                'verbose_name_plural': 'Tipos de Carta',
                'db_table': 'letter_types',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranties', to='cartas_fianzas.contractor', verbose_name='Contratista')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('letter_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranties', to='cartas_fianzas.lettertype', verbose_name='Tipo de Carta')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Garantía',
                'verbose_name_plural': 'Garantías',
                'db_table': 'warranties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('letter_number', models.CharField(help_text='Ejemplo: 010079913-000', max_length=50, verbose_name='Número de Carta')),
                ('financial_entity_address', models.CharField(max_length=50, verbose_name='Dirección de Entidad Financiera')),
                ('issue_date', models.DateField(verbose_name='Fecha de Emisión')),
                ('validity_start', models.DateField(verbose_name='Inicio de Vigencia')),
                ('validity_end', models.DateField(verbose_name='Fin de Vigencia')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('reference_document', models.CharField(blank=True, help_text='Ejemplo: INFORME 3595-2008-DO-OI/MPP 30.09.08', max_length=50, verbose_name='Documento de Referencia')),
                ('comments', models.TextField(blank=True, help_text='Observaciones adicionales sobre el movimiento', max_length=1024, verbose_name='Comentarios')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('currency_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_histories', to='cartas_fianzas.currencytype', verbose_name='Tipo de Moneda')),
                ('financial_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_histories', to='cartas_fianzas.financialentity', verbose_name='Entidad Financiera')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='cartas_fianzas.warranty', verbose_name='Garantía')),
            ],
            options={
                'verbose_name': 'Historial de Garantía',
                'verbose_name_plural': 'Historiales de Garantía',
                'db_table': 'warranty_histories',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('file_name', models.CharField(max_length=128, verbose_name='Nombre de Archivo')),
                ('file', models.FileField(upload_to='warranty_files/%Y/%m/%d/', verbose_name='Archivo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('warranty_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cartas_fianzas.warrantyhistory', verbose_name='Historial de Garantía')),
            ],
            options={
                'verbose_name': 'Archivo de Garantía',
                'verbose_name_plural': 'Archivos de Garantía',
                'db_table': 'warranty_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('description', models.CharField(help_text='Ejemplo: MANTENIMIENTO DE VIAS Y DE LA RED DE SEMAFOROS LOCAL', max_length=512, verbose_name='Descripción')),
                ('cui', models.CharField(help_text='Código Único de Inversión', max_length=10, verbose_name='CUI')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Objeto de Garantía',
                'verbose_name_plural': 'Objetos de Garantía',
                'db_table': 'warranty_objects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='warranty',
            name='warranty_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranties', to='cartas_fianzas.warrantyobject', verbose_name='Objeto de Garantía'),
        ),
        migrations.CreateModel(
            name='WarrantyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('description', models.CharField(help_text='Ejemplo: Emisión, renovación, devolución', max_length=50, verbose_name='Descripción')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Estado de Garantía',
                'verbose_name_plural': 'Estados de Garantía',
                'db_table': 'warranty_statuses',
                'ordering': ['description'],
            },
        ),
        migrations.AddField(
            model_name='warrantyhistory',
            name='warranty_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_histories', to='cartas_fianzas.warrantystatus', verbose_name='Estado de Garantía'),
        ),
    ]
