# Generated by Django 5.2 on 2025-11-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas_fianzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyobject',
            name='cui',
            field=models.CharField(blank=True, help_text='Código Único de Inversión (Opcional)', max_length=10, null=True, verbose_name='CUI'),
        ),
    ]
