# Generated by Django 5.2 on 2025-11-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas_fianzas', '0002_alter_warrantyobject_cui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='warranty_files/', verbose_name='Archivo'),
        ),
    ]
