# Generated by Django 5.2 on 2025-11-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas_fianzas', '0003_alter_warrantyfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantystatus',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el estado está activo para considerar en reportes de vencimiento', verbose_name='Activo'),
        ),
    ]
