# Generated by Django 5.2 on 2025-11-17 18:22

from django.db import migrations


def update_warranty_status_is_active(apps, schema_editor):
    """
    Migración de datos para marcar estados 3 (Devolución) y 6 (Ejecución)
    como is_active=False.
    
    Estos estados no deben considerarse en reportes de cartas vencidas.
    """
    WarrantyStatus = apps.get_model('cartas_fianzas', 'WarrantyStatus')
    
    # Marcar estado 3 (Devolución) como inactivo
    WarrantyStatus.objects.filter(id=3).update(is_active=False)
    
    # Marcar estado 6 (Ejecución) como inactivo
    WarrantyStatus.objects.filter(id=6).update(is_active=False)
    
    print("✅ Estados 3 y 6 marcados como is_active=False")


def reverse_update(apps, schema_editor):
    """
    Revertir la migración: marcar estados 3 y 6 como activos nuevamente
    """
    WarrantyStatus = apps.get_model('cartas_fianzas', 'WarrantyStatus')
    
    # Reactivar estados 3 y 6
    WarrantyStatus.objects.filter(id__in=[3, 6]).update(is_active=True)
    
    print("✅ Estados 3 y 6 revertidos a is_active=True")


class Migration(migrations.Migration):

    dependencies = [
        ('cartas_fianzas', '0004_warrantystatus_is_active'),
    ]

    operations = [
        migrations.RunPython(update_warranty_status_is_active, reverse_update),
    ]
