# Generated by Django 5.2 on 2025-12-03 17:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas_fianzas', '0005_update_warranty_status_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyhistory',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='warrantyhistory',
            name='currency_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warranty_histories', to='cartas_fianzas.currencytype', verbose_name='Tipo de Moneda'),
        ),
        migrations.AlterField(
            model_name='warrantyhistory',
            name='financial_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warranty_histories', to='cartas_fianzas.financialentity', verbose_name='Entidad Financiera'),
        ),
        migrations.AlterField(
            model_name='warrantyhistory',
            name='financial_entity_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección de Entidad Financiera'),
        ),
        migrations.AlterField(
            model_name='warrantyhistory',
            name='letter_number',
            field=models.CharField(blank=True, help_text='Ejemplo: 010079913-000. Puede ser nulo para devoluciones/ejecuciones.', max_length=50, null=True, verbose_name='Número de Carta'),
        ),
        migrations.AlterField(
            model_name='warrantyhistory',
            name='validity_end',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de Vigencia'),
        ),
        migrations.AlterField(
            model_name='warrantyhistory',
            name='validity_start',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de Vigencia'),
        ),
    ]
